; Peak-heavy preset.
; Favors needle ridges and snowy crowns, but still allows some giant wall zones.

[Surface]
Mode              = 3
RegionCellSize    = 1700
RegionBlendWidth  = 120
RegionBlendPower  = 4
RegionSmoothEdges = true

[SingleBiome]
SingleSurfaceBiome = DNA.CastleMinerZ.Terrain.WorldBuilders.TerralithLowBasePeaksBiome

[RandomRegions]
BiomeCount = 10
Biome0 = DNA.CastleMinerZ.Terrain.WorldBuilders.TerralithLowBaseCliffsBiome
Biome1 = DNA.CastleMinerZ.Terrain.WorldBuilders.TerralithLowBaseCliffsBiome
Biome2 = DNA.CastleMinerZ.Terrain.WorldBuilders.TerralithLowBasePeaksBiome
Biome3 = DNA.CastleMinerZ.Terrain.WorldBuilders.TerralithLowBasePeaksBiome
Biome4 = DNA.CastleMinerZ.Terrain.WorldBuilders.TerralithLowBasePeaksBiome
Biome5 = DNA.CastleMinerZ.Terrain.WorldBuilders.TerralithLowBasePeaksBiome
Biome6 = DNA.CastleMinerZ.Terrain.WorldBuilders.TerralithLowBaseSkybreakersBiome
Biome7 = DNA.CastleMinerZ.Terrain.WorldBuilders.TerralithLowBaseSkybreakersBiome
Biome8 = DNA.CastleMinerZ.Terrain.WorldBuilders.TerralithLowBaseSkybreakersBiome
Biome9 = DNA.CastleMinerZ.Terrain.WorldBuilders.TerralithLowBaseSkybreakersBiome
AutoIncludeCustomBiomes = false

[Overlays]
CrashSites  = false
Caves       = true
Ore         = true
HellCeiling = true
Hell        = true
Bedrock     = true
Origin      = true
Water       = false
Trees       = true

[Trees]
TreeScale        = 0.31
Threshold        = 0.66
BaseTrunkHeight  = 7
HeightVarMul     = 15
LeafRadius       = 3
LeafNoiseScale   = 0.50
LeafCutoff       = 0.20
GroundScanStartY = 126
GroundScanMinY   = 0
MinGroundHeight  = 1
